defaults:
  - framework: 
    - diffusion/cm
  - model: 
    - diffusion/unetpp_cm
  - ema: ema
  - dataset: cifar10
  - exp: exp_setting

framework:
  is_distillation: False

type: ${framework.diffusion.type}
exp_name: cm_training_default_experiment
do_training: true
do_sampling: true
num_sampling: 50000
sampling_batch: 256
rand_seed: 42
fid_during_training: true # True when calculating fid during training, otherwise, false.
n_jitted_steps: 100

framework:
  train_idx: 2

hydra:  
  output_subdir: null  
  run:  
    dir: .

