defaults:
  - framework: 
    # - diffusion/ict
    - diffusion/cm_diffusion
  - model@_group_.diffusion: 
    # - diffusion/unetpp_cm
    - diffusion/original_cm
    # - diffusion/original_ict
  - model@_group_.head: 
    # - diffusion/score_head_pde
    - diffusion/score_head
    # - diffusion/score_head_baseline
  # - ema: ema_edm
  - ema: ema
  - dataset: cifar10
  - exp: exp_setting

model:
  diffusion:
    double_heads: True

type: ${framework.diffusion.type}
exp_name: 1218_CT_double_head_for_EDM
tags: [CT, double_head]
do_training: True
do_sampling: True
num_sampling: 50000
sampling_batch: 256
rand_seed: 42
fid_during_training: True # True when calculating fid during training, otherwise, false.
n_jitted_steps: 10

available_gpus: "0, 1, 2, 3, 4, 5, 6, 7"


hydra:  
  output_subdir: null  
  run:  
    dir: .
