defaults:
  # - framework: ldm
  - framework: 
    # - diffusion/ddim
    # - diffusion/ddpm
    # - diffusion/improved_ddpm
    - diffusion/edm
  - model: 
    - autoencoder/autoencoder_kl
    - discriminator/discriminator_kl
    # - diffusion/dit_b
    # - diffusion/unet
    - diffusion/unetpp
  # - ema: ema
  - ema: ema_edm
  - dataset: cifar10
  - exp: exp_setting

# type: ddpm ddpm
type: edm
exp_name: edm_retraining
do_training: true
do_sampling: true
num_sampling: 50000
sampling_batch: 256
rand_seed: 42
fid_during_training: true # True when calculating fid during training, otherwise, false.
n_jitted_steps: 10

framework:
  train_idx: 2
  # pretrained_ae: "ldm_vq_cifar10_with_gan"

hydra:  
  output_subdir: null  
  run:  
    dir: .

