defaults:
  # - framework: ldm
  - framework: 
    # - diffusion/ddim
    # - diffusion/ddpm
    # - diffusion/improved_ddpm
    # - diffusion/edm
    # - diffusion/cm
    - diffusion/cm_diffusion
    # - diffusion/cm_dm
  - model@_group_.diffusion: 
    - diffusion/unetpp_cm
  - model@_group_.head: 
    # - diffusion/score_head_pde
    - diffusion/score_head
    # - diffusion/score_head_baseline
  # - ema: ema_edm
  - ema: ema
  - dataset: cifar10
  - exp: exp_setting

# type: ddpm ddim ldm edm (const_dist, const_train: NEW!)
# type: edm
type: ${framework.diffusion.type}
exp_name: 0919_verification_only_cm_update_with_uniform_to_propagate
# exp_name: 0919_verification_alternative_training_CD_sampling_score_feedback_dsm_recheck
do_training: true
do_sampling: true
num_sampling: 50000
sampling_batch: 256
rand_seed: 42
fid_during_training: true # True when calculating fid during training, otherwise, false.
n_jitted_steps: 10

framework:
  diffusion:
    distillation_path: None # experiments/cm_dm_230603_encoder_head_with_time_emb_1 # Exp name or pretrained model file name
    t_emb_output: True

  train_idx: 2

hydra:  
  output_subdir: null  
  run:  
    dir: .

