defaults:
  - framework: 
    - diffusion/ict
  - model@_group_.diffusion: 
    - diffusion/unetpp_ict
  - ema: ema
  - dataset: cifar10
  - exp: exp_setting

type: ${framework.diffusion.type}
exp_name: ict_pseudohuber_231206
# tags: [cm, score_feedback, param_ema]
tags: [ict]
do_training: true
do_sampling: true
num_sampling: 50000
sampling_batch: 256
rand_seed: 42
fid_during_training: true # True when calculating fid during training, otherwise, false.
n_jitted_steps: 10

framework:
  diffusion:
    distillation_path: None # experiments/cm_dm_230603_encoder_head_with_time_emb_1 # Exp name or pretrained model file name
    t_emb_output: True
  train_idx: 2

hydra:  
  output_subdir: null  
  run:  
    dir: .
