defaults:
  - framework: 
    # - diffusion/ict
    - diffusion/cm_diffusion
  - model@_group_.diffusion: 
    # - diffusion/unetpp_cm
    # - diffusion/original_cm
    - diffusion/original_ict
  - model@_group_.head: 
    # - diffusion/score_head_conv
    # - diffusion/score_head_pde
    - diffusion/score_head
    # - diffusion/score_head_large
    # - diffusion/score_head_baseline
  # - ema: ema_edm
  - ema: ema_ict
  - dataset: cifar10
  - exp: exp_setting

type: ${framework.diffusion.type}
exp_name: 0112_iCT_512_pseudo_huber_c_001
tags: [iCT]
do_training: True
do_sampling: True
num_sampling: 50000
sampling_batch: 256
rand_seed: 42
fid_during_training: True # True when calculating fid during training, otherwise, false.
n_jitted_steps: 10

available_gpus: "0, 1, 2, 3, 4, 5, 6, 7"

# framework:
#   diffusion:
#     distillation_path: None # experiments/cm_dm_230603_encoder_head_with_time_emb_1 # Exp name or pretrained model file name
    # t_emb_output: True
  # train_idx: 2

framework:
  diffusion:
    pseudo_huber_loss_c: 0.01

hydra:  
  output_subdir: null  
  run:  
    dir: .