defaults:
  # - framework: ldm
  - framework: 
    # - diffusion/ddim
    - diffusion/ddpm
    # - diffusion/improved_ddpm
  - model: 
    - autoencoder/autoencoder_kl
    - discriminator/discriminator_kl
    # - diffusion/dit_b
    - diffusion/unet
  - ema: ema
  - dataset: cifar10
  - exp: exp_setting

# type: ddpm ddpm
type: ddpm
exp_name: ddpm_speed_up
do_training: true
do_sampling: true
num_sampling: 50000
sampling_batch: 256
rand_seed: 42
fid_during_training: true # True when calculating fid during training, otherwise, false.
pmap: True

framework:
  train_idx: 2
  # pretrained_ae: "ldm_vq_cifar10_with_gan"

hydra:  
  output_subdir: null  
  run:  
    dir: .

