# Define experiment name and its path
exp:
  exp_name: "ldm_cifar10_1211"
  exp_dir: "experiments"
  sampling_dir: "sampling"
  in_process_dir : "in_process"
  checkpoint_dir: "checkpoints"
  checkpoint_prefix: ["ae_", "diffusion_"]
dataset: "cifar10"

# Define configuration of model
model:
  autoencoder:
    image_channels: 3
    n_channels: 128
    ch_mults: [1, 2, 4] # For cifar 10
    is_atten: [False, False, False]
    n_blocks: 2
    dropout_rate: 0.1
    n_heads: 4

  diffusion:
    image_channels: 3
    n_channels: 128
    ch_mults: [1, 2, 2, 2] # For cifar 10
    is_atten: [False, True, False, False]
    n_blocks: 2
    dropout_rate: 0.1
    n_heads: 4

# Define DDPM
framework:
  train_idx: 1 # 1 (AE) or 2 (Diffusion). This is only for ldm. Selected model will be trained. 
  autoencoder:
    loss: "KL" # VQ or KL
    train:
      learning_rate: 2.0e-4
      gradient_clip: 1.0
      warmup: 5000
      batch_size: 128
      total_step: 800000
      sampling_step: 10000
      saving_step: 100000
  diffusion:
    beta: [0.0001, 0.02]
    n_timestep: 1000
    loss: "l2"
    train:
      learning_rate: 2.0e-4
      gradient_clip: 1.0
      warmup: 5000
      batch_size: 128
      total_step: 800000
      sampling_step: 10000
      saving_step: 100000

# Define EMA configuration
ema:
  beta: 0.9999
  update_every: 10

sampling:
  batch_size: 256
  
rand_seed: 42
