type: "dit"
input_size: 32
patch_size: 2
in_channels: 4
hidden_size: 1152
depth: 28
num_heads: 16
mlp_ratio: 4.0
class_dropout_prob: 0.1
num_classes: 10
dropout_rate: 0.0
# learn_sigma: True
learn_sigma: ${framework.diffusion.learn_sigma}