type: "unetpp"
model_class: diffusion.model.unetpp.CMPrecond

image_channels: 3
n_channels: 128
label_dim:  0
# augment_dim: 0
augment_dim: 9

ch_mults: [2, 2, 2]
is_atten: [False, True, False]
n_blocks: 4
n_heads: 1
n_groups: 32
skip_rescale: True
dropout_rate: 0.0
label_dropout_rate: 0.0

embedding_type: fourier
encoder_type : residual
decoder_type : standard
resample_filter: [1, 3, 3, 1]
learn_sigma: False