defaults:
  - autoencoder/autoencoder_kl
  # - diffusion/ddpm
  - diffusion/improved_ddpm

framework_class: framework.LDM

train_idx: ??? # 1 (AE) or 2 (Diffusion). This is only for ldm. Selected model will be trained. 