type: "cm"
n_timestep: 18
loss: lpips # l2, l1, lpips
# noise_schedule: linear # cosine, linear
learn_sigma: False

# Consistency distillation or Consistency training
is_distillation: False
distillation_path: experiments/edm_porting_from_torch_ve/checkpoints # Exp name or pretrained model file name
target_model_ema_decay: 0
params_ema_for_training: [0.9, 2, 150] # mu_0, s_0, s_1

# Sigma : Assume that the process is performing VP
sigma_min: 0.002
sigma_max: 80
rho: 7

deterministic_sampling: True
S_churn: 30
S_min: 0.01
S_max: 1
S_noise: 1.007

# Loading Checkpoint
# torso_checkpoint: 'pretrained_models/cd_750k'
torso_checkpoint_path: null # None
# head_checkpoint_path: "experiments/0906_verification_unet_block_1/checkpoints" # None
head_checkpoint_path: null
initialize_previous_training_step: False

# Option for freezing CM during training
CM_freeze: False
joint_training: False
alternative_training: False
only_cm_training: True
# joint training and alternative training should be toggled together 

# Option for sigma sampling for head, torso
# EDM, CD, CT, 
# EDM_Quantization, uniform_Quantization
# Bernoulli, Bernoulli_Quantization, Bernoulli_uniform_Quantization, 
sigma_sampling_head: EDM
sigma_sampling_torso: CT
sigma_sampling_joint: CT

# Common training procedure

# Head training procedure
head_martingale_loss_hyperparam: 0.1
head_connection_loss: False # The name is temporarily used for now.


# Torso training procedure
gradient_flow_from_head: False
score_feedback: False
score_feedback_type: "threshold" # interpolation, threshold # for now, interpolation is not supported
score_feedback_threshold: 1.0
torso_connection_loss: False # The name is temporarily used for now.
torso_connection_threshold: 150000

# augment_rate: 0.12
score_pde_regularizer: False
dh_dx_inv_weight: 1.0
dh_dt_weight: 1.0

train:
  learning_rate: 4.0e-4
  # learning_rate: 2.0e-4
  # gradient_clip: 1.0
  # warmup: 5000
  # warmup: 19532 # int(10e6 / ${.batch_size})
  batch_size: 512
  total_step: 800000
  sampling_step: 10000
  saving_step: 100000
  optimizer:
    type: "radam"
