type: "edm"
beta: [0.0001, 0.02]
n_timestep: 18
loss: "l2"
noise_schedule: linear # cosine, linear
learn_sigma: False

# Sigma : Assume that the process is performing VP
sigma_min: 0.002
sigma_max: 80
rho: 7

deterministic_sampling: False
S_churn: 30
S_min: 0.01
S_max: 1
S_noise: 1.007

augment_rate: 0.12

train:
  learning_rate: 1.0e-3
  # gradient_clip: 1.0
  # warmup: 5000
  warmup: 19532 # int(10e6 / ${.batch_size})
  batch_size: 512
  total_step: 400000
  sampling_step: 10000
  saving_step: 100000
  optimizer:
    type: "Adam"
