type: "edm"
beta: [0.0001, 0.02]
n_timestep: 18
loss: "l2"
noise_schedule: linear # cosine, linear
learn_sigma: False

# Sigma
sigma_min: 0.002
sigma_max: 80
rho: 7

train:
  learning_rate: 1.0e-3
  # gradient_clip: 1.0
  warmup: 5000
  batch_size: 512
  total_step: 400000
  sampling_step: 10000
  saving_step: 100000
  optimizer:
    type: "Adam"
